const RouteName = {
    SPLASH_SCREEN: "SplashScreen",
    GET_STARTED_SCREEN: "GetstartedSliderscreen",
    LOGIN_AND_REGISTRATION: "LoginRegistration",
    WELCOME_SCREEN: "WelcomeSumnya",
    LOCATION_HOME_OFFICE_SCREEN: "LocationHomeOfficeScreen",
    CONFORMLOCATION_SET: "ConfirmLocation",
    HOME_SCREEN: "Homescreen",
    POPULAR_SCREEN: "SearchPopularMedicine",
    HOSPITAL_MEDICINE_SCREEN: "SearchPopular",
    PRODUCT_LIST_ITEM: "ProductItemList",
    PRODUCT_DETAILS_SCREEN: "ProductDetailesScreen",
    OFFERS_TAB: "Offer",
    CART_TAB: "Cart",
    CHECK_OUT: "CheckOutScreen",
    ACCOUNT_TAB_SET: "Account",
    HOME_TAB: "Home",
    PAYMENT_SCREEN: "PaymentScreen",
    SETTTING_SCREEN: "SettingsScreen",
    ALL_BOOK_MARK_SCREEN: "AllBookMarkScreen",
    YOUR_ORDER_SCREEN: "My Orders",
    OTP_VERIFY_SCREEN: "OtpVeryfyScreen",
    ORDER_TAB_SCREEN: "TrackOrderitem",
    CREDIT_CARD_SCREEN_SET: "CreditCardScreen",
    PAYMENT_SUCCESSFULLY: "PaymentSuccessFully",
    RATING_SCREEN_SET: "RatingScreen",
    EDIT_LOCATION_SCREEN: "EditLocationScreen",
    EDIT_PROFILE_SCREEN: "EditProfileScreen",
    FORGET_PASSWORD_SCREEN: "ForgotPassword",
    HELP_SCREEN: "HelpScreen",
    NOTIFICATION_SCREEN: "NotificationScreen",
    CHAT_SCREEN: "ChatScreen",
    TRANSLATION_SCREEN: "TranslationScreen",
    TABNAVIGATOR: "TabNavigator"

}
export default RouteName;