import { StyleSheet, Platform } from 'react-native';
import { SF, SH, SW, Fonts, Colors, } from '../../utils';

export default StyleSheet.create({
  minstyleviewphotograpgy: {
    flexDirection: 'row',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
  },
  bgcolorset: {
    backgroundColor: Colors.bg_screen
  },
  minviewsigninscreen: {
    width: '100%',
    paddingBottom: SH(160),
  },
  minflexview: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  setbgcolorviewmin: {
    backgroundColor: Colors.anti_flash_white_color,
    padding: SW(20),
    borderRadius: SW(20),
  },
  bgwhiteview: {
    backgroundColor: Colors.bgwhite,
    padding: SW(20),
    borderRadius: SW(20),
  },
  pizaiconstyle: {
    fontSize: SF(20),
    fontWeight: '700',
    fontFamily: Fonts.Metropolis_Medium,
  },
  fexrowseticonview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  twoiconflexset: {
    flexDirection: 'row'
  },
  iconstyleset: {
    marginLeft: SW(20),
  },
  bgcolorinstart: {
    width: SW(20),
    height: SH(20),
    marginRight: SW(10),
    borderRadius: SW(100),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  serticonse: {
    position: 'relative',
    left: SW(0.2),
    top: SH(-1),
  },
  setbgcolorviewflexview: {
    flexDirection: 'row',
    marginTop: SH(10),
    alignItems: 'center',
  },
  starttextsyuyle: {
    fontSize: SF(14),
    color: Colors.chinese_black,
    fontWeight: '700',
    fontFamily: Fonts.Metropolis_Medium,
  },
  settextpizastyle: {
    fontSize: SF(14),
    color: Colors.gray_text_color,
    fontWeight: '600',
    fontFamily: Fonts.Metropolis_Medium,
    paddingTop: SH(10),
  },
  flexrowsetpaddle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: SH(15),
    paddingLeft: SW(20),
  },
  settextoutlettext: {
    fontSize: SF(14),
    color: Colors.chinese_black,
    fontWeight: '700',
    fontFamily: Fonts.Metropolis_Medium,
    marginRight: SW(20),
  },
  viranichockflexview: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viranichocktextset: {
    fontSize: SF(14),
    color: Colors.gray_text_color,
    fontWeight: '600',
    fontFamily: Fonts.Metropolis_Medium,
    marginRight: SW(10),
  },
  shortdowniconstyle: {
    position: 'relative',
    top: SH(-3),
  },
  flexrowsetonetext: {
    flexDirection: 'row',
    paddingTop: SH(15),
    alignItems: 'center',
    borderTopColor: Colors.LighGrey,
    borderTopWidth: SW(1),
    marginTop: SH(20),
  },
  onetextsetbgcoloe: {
    fontSize: SF(16),
    color: Colors.theme_background,
    fontWeight: '700',
    fontFamily: Fonts.Metropolis_Medium,
    marginRight: SW(10),
  },
  extratextset: {
    fontSize: SF(11),
    color: Colors.theme_background,
    fontWeight: '600',
    fontFamily: Fonts.Metropolis_Medium,
    marginRight: SW(10),
    width: '89%',
    marginTop: SH(3),
  },
  menuflexcenter: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingTop: SH(20),
  },
  setmenutext: {
    fontSize: SF(16),
    color: Colors.theme_background,
    fontWeight: '700',
    fontFamily: Fonts.Metropolis_Medium,
    paddingBottom: SH(20),
  },
  imagsetstylehati: {
    width: SW(130),
    height: SH(120),
    borderRadius: SW(7),
  },
  imagsetstyleslider: {
    width: SW(30),
    height: SH(30),
    borderRadius: SW(7),
  },
  flexrowsetterxt: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SW(15),
    paddingVertical: SH(20),
  },
  boldtextstyle: {
    fontSize: SF(15),
    color: Colors.theme_background,
    fontWeight: '700',
    fontFamily: Fonts.Metropolis_Medium,
  },
  setgreentext: {
    fontSize: SF(14),
    color: Colors.gray_text_color,
    fontWeight: '600',
    fontFamily: Fonts.Metropolis_Medium,
  },
  flexrowdotwithtext: {
    flexDirection: 'row',
  },
  setdottextround: {
    backgroundColor: Colors.polished_pine_color,
    fontWeight: '700',
    width: SW(10),
    height: SW(10),
    borderRadius: SW(100),
  },
  setborderround: {
    borderWidth: SW(1),
    width: SW(22),
    height: SH(23),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: SW(5),
    border_color: Colors.polished_pine_color,
    marginRight: SW(10),
    marginBottom: SH(7),
  },
  pricetextsetruppiss: {
    fontSize: SF(17),
    color: Colors.theme_background,
    fontWeight: '700',
    fontFamily: Fonts.Metropolis_Medium,
    paddingTop: SH(5),
  },
  setmarginright: {
    marginLeft: SW(2),
    color: Colors.big_foot_feet_color,
    fontFamily: Fonts.Metropolis_Medium,
  },
  setratingminview: {
    flexDirection: 'row',
    paddingTop: SH(6),
  },
  setminview: {
    borderBottomColor: Colors.LighGrey,
    borderStyle: 'dashed',
    borderBottomWidth: SW(1),
  },
  addtextstyleset: {
    flexDirection: 'row',
    width: SW(100),
    justifyContent: 'space-between',
    paddingHorizontal: SW(5),
    backgroundColor: Colors.bgwhite,
    height: SH(30),
    alignItems: 'center',
    position: 'absolute',
    bottom: SH(-12),
    shadowOffset: {
      width: 0,
      height: Platform.OS === 'ios' ? 2 : 25,
    },
    shadowOpacity: 0.58,
    shadowRadius: Platform.OS === 'ios' ? 2 : 25,
    elevation: Platform.OS === 'ios' ? 1 : 4,
    borderRadius: SW(7),
  },
  addtextstylesettwo: {
    flexDirection: 'row',
    width: SW(100),
    justifyContent: 'center',
    paddingHorizontal: SW(5),
    backgroundColor: Colors.bgwhite,
    height: SH(30),
    alignItems: 'center',
    position: 'absolute',
    bottom: SH(-12),
    shadowOffset: {
      width: 0,
      height: Platform.OS === 'ios' ? 2 : 25,
    },
    shadowOpacity: 0.58,
    shadowRadius: Platform.OS === 'ios' ? 2 : 25,
    elevation: Platform.OS === 'ios' ? 1 : 4,
    borderRadius: SW(7),
  },
  centerviewadd: {
    flexDirection: 'row',
    justifyContent: 'center'
  },
  simpletextaddstylset: {
    fontSize: SF(16),
    color: Colors.theme_background,
    fontWeight: '700',
    fontFamily: Fonts.Metropolis_Medium,
  },
  customissaletext: {
    fontSize: SF(12),
    color: Colors.gray_text_color,
    fontWeight: '500',
    fontFamily: Fonts.Metropolis_Medium,
    textAlign: 'center',
    paddingTop: SH(15),
  },
  setbuttontextstyle: {
    backgroundColor: Colors.bgwhite,
    fontSize: SF(14.5),
    color: Colors.theme_background,
    fontWeight: '500',
    fontFamily: Fonts.Metropolis_Medium,
    textAlign: 'center',
  },
  setbuttontextstyletwo: {
    backgroundColor: Colors.bgwhite,
    fontSize: SF(14.5),
    color: Colors.theme_background,
    fontWeight: '500',
    fontFamily: Fonts.Metropolis_Medium,
    textAlign: 'center',
  },
  setwidthbutton: {
    width: '35%',
    marginRight: SW(20),
    borderWidth: SW(1),
    height: SH(30),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: SW(100),
  },
  setbuttontext: {
    color: Colors.polished_pine_color,
    fontSize: SF(14),
    paddingTop: SH(3),
  },
  setbuttontexttwo: {
    color: Colors.gray_text_color,
    fontSize: SF(14),
    paddingTop: SH(3),
  },
  flexbuttonsettwostyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginLeft: SW(15),
    paddingBottom: SH(10),
  },
  bordersetround: {
    width: '50%'
  },
  orijnalytextstle: {
    paddingTop: SH(10),
    fontSize: SF(12),
    color: Colors.gray_text_color,
    fontWeight: '500',
    fontFamily: Fonts.Metropolis_Medium,
  },
  plusandminusflexview: {
    flexDirection: 'row',
    borderWidth: SW(1),
    alignItems: 'center',
    justifyContent: 'space-between',
    border_color: Colors.bgwhite,
    borderRadius: SW(100),
    width: SW(130),
    paddingHorizontal: SW(15),
    paddingTop: SH(5),
  },
  pricetextsetview: {
    color: Colors.polished_pine_color,
    fontSize: SF(18),
    fontWeight: '600',
    fontFamily: Fonts.Poppins_Medium,
  },
  carousalContainer: {
    flexDirection: "row",
    width: "100%",
  },
  title: {
    fontSize: SF(28),
    color: Colors.black_text_color,
    fontSize: SF(18),
    fontWeight: '700',
    fontFamily: Fonts.Poppins_Medium,
  },
  subtitle: {
    color: Colors.gray_text_color,
    fontSize: SF(12),
    fontWeight: '600',
    fontFamily: Fonts.Poppins_Medium,
  },

  imagsetstyle: {
    width: SW(30),
    height: SH(30),
    borderRadius: SW(7),
  },
  setviewsliderflex: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: SW(15),
    paddingVertical: SW(20),
  },
  titleContainer: {
    marginLeft: SW(20),
  },
  seemoretextstyle: {
    fontWeight: '700',
    color: Colors.theme_background,
    lineHeight: SH(30),
    fontFamily: Fonts.Roboto_Regular,
    fontSize: SF(15),
    position: 'relative',
    top: SH(5)
  },
  seemlesstextsyle: {
    fontWeight: '700',
    color: Colors.theme_background,
    fontFamily: Fonts.Roboto_Regular,
    fontSize: SF(15),
  },
  setbgcolorbottom: {
    paddingVertical: SH(10),
    backgroundColor: Colors.theme_background,
    width: '100%',
    borderRadius: SW(7),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SW(10),
    shadowOffset: {
      width: 0,
      height: Platform.OS === 'ios' ? 2 : 25,
    },
    shadowOpacity: 0.58,
    shadowRadius: Platform.OS === 'ios' ? 2 : 25,
    elevation: Platform.OS === 'ios' ? 1 : 8,
  },
  marginbottomspaceset: {
    marginBottom: SH(30),
  },
  settextstyle: {
    color: Colors.white_text_color,
    fontFamily: Fonts.Metropolis_Medium,
    fontSize: SF(14),
  },
  viewchartstyleset: {
    color: Colors.white_text_color,
    fontFamily: Fonts.Metropolis_Medium,
    fontSize: SF(16),
    fontWeight: '700',
  },
  positionsetabsolute: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  setbottomviewwidth: {
    width: '95%',
  },
  setborderonesetdot: {
    backgroundColor: Colors.bggray,
    width: SW(7),
    height: SW(7),
    borderRadius: SW(100),
  },
  setborderline: {
    backgroundColor: Colors.LighGrey,
    width: SW(2),
    height: SH(30),
    marginLeft: SW(2),
  },
  postionsetabsolute: {
    position: 'absolute',
    top: SH(20),
    left: 0,
  }
});
